language: nix
sudo: true
os:
- linux
- osx
env:
  global:
  - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/09c7601c204016c8ecdefd474f721fb841e834df.tar.gz
script:
- nix-env -i hello
- hello
